version: '3'
services:
  hugo:
    image: klakegg/hugo:latest
    volumes:
      - ${PWD}/kbsite:/src
    ports:
      - "20252:20252"
    command: ["server", "-w", "--bind=0.0.0.0", "--port", "20252"]
